name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: DockerHub Login
      run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASS}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sflorezs1/great-idea:latest \
        --build-arg DB_DB=${{secrets.DB_DB}} \
        --build-arg DB_USER=${{secrets.DB_USER}} \
        --build-arg DB_HOST=${{secrets.DB_HOST}} \
        --build-arg DB_PASS=${{secrets.DB_PASS}}
    - name: DockerHub Push
      run: docker push sflorezs1/great-idea
